export const scheduleMeta = {
  sourceLabel: "FIFA World Cup 2026 match schedule PDF",
  sourceUrl:
    "https://digitalhub.fifa.com/asset/4b5d4417-3343-4732-9cdf-14b6662af407/FWC26-Match-Schedule_English.pdf",
  mappingSourceLabel: "WorldCupHub schedule HTML table",
  mappingSourceUrl: "https://worldcuphub.io/en/schedule",
  extractedAt: "2026-05-22",
  note:
    "Match teams and numbering are aligned to the FIFA schedule PDF. Date, city, stadium and ET kickoff values are mapped from a text-readable schedule table and should be re-checked against FIFA before production publication."
};

export const matches = [
  {
    matchNumber: 1,
    stage: "Group stage",
    group: "A",
    date: "2026-06-11",
    dateLabel: "Thursday, June 11, 2026",
    kickoffET: "16:00",
    home: "Mexico",
    away: "South Africa",
    city: "Mexico City",
    citySlug: "mexico-city",
    stadium: "Estadio Banorte",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 2,
    stage: "Group stage",
    group: "A",
    date: "2026-06-11",
    dateLabel: "Thursday, June 11, 2026",
    kickoffET: "23:00",
    home: "South Korea",
    away: "Czechia",
    city: "Guadalajara",
    citySlug: "guadalajara",
    stadium: "Estadio Akron",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 3,
    stage: "Group stage",
    group: "B",
    date: "2026-06-12",
    dateLabel: "Friday, June 12, 2026",
    kickoffET: "16:00",
    home: "Canada",
    away: "Bosnia & Herzegovina",
    city: "Toronto",
    citySlug: "toronto",
    stadium: "BMO Field",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 4,
    stage: "Group stage",
    group: "D",
    date: "2026-06-12",
    dateLabel: "Friday, June 12, 2026",
    kickoffET: "22:00",
    home: "United States",
    away: "Paraguay",
    city: "Los Angeles",
    citySlug: "los-angeles",
    stadium: "SoFi Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 5,
    stage: "Group stage",
    group: "B",
    date: "2026-06-13",
    dateLabel: "Saturday, June 13, 2026",
    kickoffET: "16:00",
    home: "Qatar",
    away: "Switzerland",
    city: "San Francisco Bay Area",
    citySlug: "san-francisco",
    stadium: "Levi's Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 6,
    stage: "Group stage",
    group: "C",
    date: "2026-06-13",
    dateLabel: "Saturday, June 13, 2026",
    kickoffET: "19:00",
    home: "Brazil",
    away: "Morocco",
    city: "New York New Jersey",
    citySlug: "new-york",
    stadium: "MetLife Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 7,
    stage: "Group stage",
    group: "E",
    date: "2026-06-13",
    dateLabel: "Saturday, June 13, 2026",
    kickoffET: "20:00",
    home: "Ivory Coast",
    away: "Ecuador",
    city: "Philadelphia",
    citySlug: "philadelphia",
    stadium: "Lincoln Financial Field",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 8,
    stage: "Group stage",
    group: "C",
    date: "2026-06-13",
    dateLabel: "Saturday, June 13, 2026",
    kickoffET: "22:00",
    home: "Haiti",
    away: "Scotland",
    city: "Boston",
    citySlug: "boston",
    stadium: "Gillette Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 9,
    stage: "Group stage",
    group: "F",
    date: "2026-06-13",
    dateLabel: "Saturday, June 13, 2026",
    kickoffET: "23:00",
    home: "Sweden",
    away: "Tunisia",
    city: "Monterrey",
    citySlug: "monterrey",
    stadium: "Estadio BBVA",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 10,
    stage: "Group stage",
    group: "D",
    date: "2026-06-14",
    dateLabel: "Sunday, June 14, 2026",
    kickoffET: "01:00",
    home: "Australia",
    away: "Türkiye",
    city: "Vancouver",
    citySlug: "vancouver",
    stadium: "BC Place",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 11,
    stage: "Group stage",
    group: "E",
    date: "2026-06-14",
    dateLabel: "Sunday, June 14, 2026",
    kickoffET: "14:00",
    home: "Germany",
    away: "Curaçao",
    city: "Houston",
    citySlug: "houston",
    stadium: "NRG Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 12,
    stage: "Group stage",
    group: "F",
    date: "2026-06-14",
    dateLabel: "Sunday, June 14, 2026",
    kickoffET: "17:00",
    home: "Netherlands",
    away: "Japan",
    city: "Dallas",
    citySlug: "dallas",
    stadium: "AT&T Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 13,
    stage: "Group stage",
    group: "H",
    date: "2026-06-15",
    dateLabel: "Monday, June 15, 2026",
    kickoffET: "13:00",
    home: "Spain",
    away: "Cape Verde",
    city: "Atlanta",
    citySlug: "atlanta",
    stadium: "Mercedes-Benz Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 14,
    stage: "Group stage",
    group: "G",
    date: "2026-06-15",
    dateLabel: "Monday, June 15, 2026",
    kickoffET: "16:00",
    home: "Belgium",
    away: "Egypt",
    city: "Seattle",
    citySlug: "seattle",
    stadium: "Lumen Field",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 15,
    stage: "Group stage",
    group: "H",
    date: "2026-06-15",
    dateLabel: "Monday, June 15, 2026",
    kickoffET: "19:00",
    home: "Saudi Arabia",
    away: "Uruguay",
    city: "Miami",
    citySlug: "miami",
    stadium: "Hard Rock Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 16,
    stage: "Group stage",
    group: "G",
    date: "2026-06-15",
    dateLabel: "Monday, June 15, 2026",
    kickoffET: "22:00",
    home: "Iran",
    away: "New Zealand",
    city: "Los Angeles",
    citySlug: "los-angeles",
    stadium: "SoFi Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 17,
    stage: "Group stage",
    group: "J",
    date: "2026-06-15",
    dateLabel: "Monday, June 15, 2026",
    kickoffET: "22:00",
    home: "Argentina",
    away: "Algeria",
    city: "Kansas City",
    citySlug: "kansas-city",
    stadium: "GEHA Field at Arrowhead Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 18,
    stage: "Group stage",
    group: "J",
    date: "2026-06-16",
    dateLabel: "Tuesday, June 16, 2026",
    kickoffET: "01:00",
    home: "Austria",
    away: "Jordan",
    city: "San Francisco Bay Area",
    citySlug: "san-francisco",
    stadium: "Levi's Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 19,
    stage: "Group stage",
    group: "K",
    date: "2026-06-16",
    dateLabel: "Tuesday, June 16, 2026",
    kickoffET: "14:00",
    home: "Portugal",
    away: "DR Congo",
    city: "Houston",
    citySlug: "houston",
    stadium: "NRG Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 20,
    stage: "Group stage",
    group: "I",
    date: "2026-06-16",
    dateLabel: "Tuesday, June 16, 2026",
    kickoffET: "16:00",
    home: "France",
    away: "Senegal",
    city: "New York New Jersey",
    citySlug: "new-york",
    stadium: "MetLife Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 21,
    stage: "Group stage",
    group: "L",
    date: "2026-06-16",
    dateLabel: "Tuesday, June 16, 2026",
    kickoffET: "17:00",
    home: "England",
    away: "Croatia",
    city: "Dallas",
    citySlug: "dallas",
    stadium: "AT&T Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 22,
    stage: "Group stage",
    group: "I",
    date: "2026-06-16",
    dateLabel: "Tuesday, June 16, 2026",
    kickoffET: "19:00",
    home: "Iraq",
    away: "Norway",
    city: "Boston",
    citySlug: "boston",
    stadium: "Gillette Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 23,
    stage: "Group stage",
    group: "L",
    date: "2026-06-16",
    dateLabel: "Tuesday, June 16, 2026",
    kickoffET: "20:00",
    home: "Ghana",
    away: "Panama",
    city: "Toronto",
    citySlug: "toronto",
    stadium: "BMO Field",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 24,
    stage: "Group stage",
    group: "K",
    date: "2026-06-16",
    dateLabel: "Tuesday, June 16, 2026",
    kickoffET: "23:00",
    home: "Uzbekistan",
    away: "Colombia",
    city: "Mexico City",
    citySlug: "mexico-city",
    stadium: "Estadio Banorte",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 25,
    stage: "Group stage",
    group: "A",
    date: "2026-06-18",
    dateLabel: "Thursday, June 18, 2026",
    kickoffET: "13:00",
    home: "Czechia",
    away: "South Africa",
    city: "Atlanta",
    citySlug: "atlanta",
    stadium: "Mercedes-Benz Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 26,
    stage: "Group stage",
    group: "B",
    date: "2026-06-18",
    dateLabel: "Thursday, June 18, 2026",
    kickoffET: "16:00",
    home: "Switzerland",
    away: "Bosnia & Herzegovina",
    city: "Los Angeles",
    citySlug: "los-angeles",
    stadium: "SoFi Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 27,
    stage: "Group stage",
    group: "B",
    date: "2026-06-18",
    dateLabel: "Thursday, June 18, 2026",
    kickoffET: "19:00",
    home: "Canada",
    away: "Qatar",
    city: "Vancouver",
    citySlug: "vancouver",
    stadium: "BC Place",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 28,
    stage: "Group stage",
    group: "A",
    date: "2026-06-18",
    dateLabel: "Thursday, June 18, 2026",
    kickoffET: "22:00",
    home: "Mexico",
    away: "South Korea",
    city: "Guadalajara",
    citySlug: "guadalajara",
    stadium: "Estadio Akron",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 29,
    stage: "Group stage",
    group: "D",
    date: "2026-06-19",
    dateLabel: "Friday, June 19, 2026",
    kickoffET: "16:00",
    home: "United States",
    away: "Australia",
    city: "Seattle",
    citySlug: "seattle",
    stadium: "Lumen Field",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 30,
    stage: "Group stage",
    group: "C",
    date: "2026-06-19",
    dateLabel: "Friday, June 19, 2026",
    kickoffET: "19:00",
    home: "Scotland",
    away: "Morocco",
    city: "Boston",
    citySlug: "boston",
    stadium: "Gillette Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 31,
    stage: "Group stage",
    group: "E",
    date: "2026-06-19",
    dateLabel: "Friday, June 19, 2026",
    kickoffET: "21:00",
    home: "Ecuador",
    away: "Curaçao",
    city: "Kansas City",
    citySlug: "kansas-city",
    stadium: "GEHA Field at Arrowhead Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 32,
    stage: "Group stage",
    group: "C",
    date: "2026-06-19",
    dateLabel: "Friday, June 19, 2026",
    kickoffET: "22:00",
    home: "Brazil",
    away: "Haiti",
    city: "Philadelphia",
    citySlug: "philadelphia",
    stadium: "Lincoln Financial Field",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 33,
    stage: "Group stage",
    group: "D",
    date: "2026-06-19",
    dateLabel: "Friday, June 19, 2026",
    kickoffET: "22:00",
    home: "Türkiye",
    away: "Paraguay",
    city: "San Francisco Bay Area",
    citySlug: "san-francisco",
    stadium: "Levi's Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 34,
    stage: "Group stage",
    group: "F",
    date: "2026-06-20",
    dateLabel: "Saturday, June 20, 2026",
    kickoffET: "14:00",
    home: "Netherlands",
    away: "Sweden",
    city: "Houston",
    citySlug: "houston",
    stadium: "NRG Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 35,
    stage: "Group stage",
    group: "E",
    date: "2026-06-20",
    dateLabel: "Saturday, June 20, 2026",
    kickoffET: "17:00",
    home: "Germany",
    away: "Ivory Coast",
    city: "Toronto",
    citySlug: "toronto",
    stadium: "BMO Field",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 36,
    stage: "Group stage",
    group: "F",
    date: "2026-06-20",
    dateLabel: "Saturday, June 20, 2026",
    kickoffET: "22:00",
    home: "Tunisia",
    away: "Japan",
    city: "Monterrey",
    citySlug: "monterrey",
    stadium: "Estadio BBVA",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 37,
    stage: "Group stage",
    group: "G",
    date: "2026-06-20",
    dateLabel: "Saturday, June 20, 2026",
    kickoffET: "22:00",
    home: "New Zealand",
    away: "Egypt",
    city: "Vancouver",
    citySlug: "vancouver",
    stadium: "BC Place",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 38,
    stage: "Group stage",
    group: "H",
    date: "2026-06-21",
    dateLabel: "Sunday, June 21, 2026",
    kickoffET: "13:00",
    home: "Spain",
    away: "Saudi Arabia",
    city: "Atlanta",
    citySlug: "atlanta",
    stadium: "Mercedes-Benz Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 39,
    stage: "Group stage",
    group: "G",
    date: "2026-06-21",
    dateLabel: "Sunday, June 21, 2026",
    kickoffET: "16:00",
    home: "Belgium",
    away: "Iran",
    city: "Los Angeles",
    citySlug: "los-angeles",
    stadium: "SoFi Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 40,
    stage: "Group stage",
    group: "H",
    date: "2026-06-21",
    dateLabel: "Sunday, June 21, 2026",
    kickoffET: "19:00",
    home: "Uruguay",
    away: "Cape Verde",
    city: "Miami",
    citySlug: "miami",
    stadium: "Hard Rock Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 41,
    stage: "Group stage",
    group: "J",
    date: "2026-06-22",
    dateLabel: "Monday, June 22, 2026",
    kickoffET: "14:00",
    home: "Argentina",
    away: "Austria",
    city: "Dallas",
    citySlug: "dallas",
    stadium: "AT&T Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 42,
    stage: "Group stage",
    group: "I",
    date: "2026-06-22",
    dateLabel: "Monday, June 22, 2026",
    kickoffET: "18:00",
    home: "France",
    away: "Iraq",
    city: "Philadelphia",
    citySlug: "philadelphia",
    stadium: "Lincoln Financial Field",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 43,
    stage: "Group stage",
    group: "L",
    date: "2026-06-22",
    dateLabel: "Monday, June 22, 2026",
    kickoffET: "20:00",
    home: "Panama",
    away: "Croatia",
    city: "Toronto",
    citySlug: "toronto",
    stadium: "BMO Field",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 44,
    stage: "Group stage",
    group: "I",
    date: "2026-06-22",
    dateLabel: "Monday, June 22, 2026",
    kickoffET: "21:00",
    home: "Norway",
    away: "Senegal",
    city: "New York New Jersey",
    citySlug: "new-york",
    stadium: "MetLife Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 45,
    stage: "Group stage",
    group: "K",
    date: "2026-06-22",
    dateLabel: "Monday, June 22, 2026",
    kickoffET: "23:00",
    home: "Colombia",
    away: "DR Congo",
    city: "Guadalajara",
    citySlug: "guadalajara",
    stadium: "Estadio Akron",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 46,
    stage: "Group stage",
    group: "K",
    date: "2026-06-23",
    dateLabel: "Tuesday, June 23, 2026",
    kickoffET: "14:00",
    home: "Portugal",
    away: "Uzbekistan",
    city: "Houston",
    citySlug: "houston",
    stadium: "NRG Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 47,
    stage: "Group stage",
    group: "L",
    date: "2026-06-23",
    dateLabel: "Tuesday, June 23, 2026",
    kickoffET: "17:00",
    home: "England",
    away: "Ghana",
    city: "Boston",
    citySlug: "boston",
    stadium: "Gillette Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 48,
    stage: "Group stage",
    group: "J",
    date: "2026-06-23",
    dateLabel: "Tuesday, June 23, 2026",
    kickoffET: "20:00",
    home: "Jordan",
    away: "Algeria",
    city: "San Francisco Bay Area",
    citySlug: "san-francisco",
    stadium: "Levi's Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 49,
    stage: "Group stage",
    group: "B",
    date: "2026-06-24",
    dateLabel: "Wednesday, June 24, 2026",
    kickoffET: "16:00",
    home: "Switzerland",
    away: "Canada",
    city: "Vancouver",
    citySlug: "vancouver",
    stadium: "BC Place",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 50,
    stage: "Group stage",
    group: "B",
    date: "2026-06-24",
    dateLabel: "Wednesday, June 24, 2026",
    kickoffET: "16:00",
    home: "Bosnia & Herzegovina",
    away: "Qatar",
    city: "Seattle",
    citySlug: "seattle",
    stadium: "Lumen Field",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 51,
    stage: "Group stage",
    group: "C",
    date: "2026-06-24",
    dateLabel: "Wednesday, June 24, 2026",
    kickoffET: "19:00",
    home: "Scotland",
    away: "Brazil",
    city: "Miami",
    citySlug: "miami",
    stadium: "Hard Rock Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 52,
    stage: "Group stage",
    group: "C",
    date: "2026-06-24",
    dateLabel: "Wednesday, June 24, 2026",
    kickoffET: "19:00",
    home: "Morocco",
    away: "Haiti",
    city: "Atlanta",
    citySlug: "atlanta",
    stadium: "Mercedes-Benz Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 53,
    stage: "Group stage",
    group: "F",
    date: "2026-06-24",
    dateLabel: "Wednesday, June 24, 2026",
    kickoffET: "20:00",
    home: "Japan",
    away: "Sweden",
    city: "Dallas",
    citySlug: "dallas",
    stadium: "AT&T Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 54,
    stage: "Group stage",
    group: "F",
    date: "2026-06-24",
    dateLabel: "Wednesday, June 24, 2026",
    kickoffET: "20:00",
    home: "Tunisia",
    away: "Netherlands",
    city: "Kansas City",
    citySlug: "kansas-city",
    stadium: "GEHA Field at Arrowhead Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 55,
    stage: "Group stage",
    group: "A",
    date: "2026-06-24",
    dateLabel: "Wednesday, June 24, 2026",
    kickoffET: "22:00",
    home: "Czechia",
    away: "Mexico",
    city: "Mexico City",
    citySlug: "mexico-city",
    stadium: "Estadio Banorte",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 56,
    stage: "Group stage",
    group: "A",
    date: "2026-06-24",
    dateLabel: "Wednesday, June 24, 2026",
    kickoffET: "22:00",
    home: "South Africa",
    away: "South Korea",
    city: "Monterrey",
    citySlug: "monterrey",
    stadium: "Estadio BBVA",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 57,
    stage: "Group stage",
    group: "D",
    date: "2026-06-24",
    dateLabel: "Wednesday, June 24, 2026",
    kickoffET: "23:00",
    home: "Türkiye",
    away: "United States",
    city: "Los Angeles",
    citySlug: "los-angeles",
    stadium: "SoFi Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 58,
    stage: "Group stage",
    group: "D",
    date: "2026-06-24",
    dateLabel: "Wednesday, June 24, 2026",
    kickoffET: "23:00",
    home: "Paraguay",
    away: "Australia",
    city: "San Francisco Bay Area",
    citySlug: "san-francisco",
    stadium: "Levi's Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 59,
    stage: "Group stage",
    group: "E",
    date: "2026-06-25",
    dateLabel: "Thursday, June 25, 2026",
    kickoffET: "17:00",
    home: "Ecuador",
    away: "Germany",
    city: "New York New Jersey",
    citySlug: "new-york",
    stadium: "MetLife Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 60,
    stage: "Group stage",
    group: "E",
    date: "2026-06-25",
    dateLabel: "Thursday, June 25, 2026",
    kickoffET: "17:00",
    home: "Curaçao",
    away: "Ivory Coast",
    city: "Philadelphia",
    citySlug: "philadelphia",
    stadium: "Lincoln Financial Field",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 61,
    stage: "Group stage",
    group: "H",
    date: "2026-06-25",
    dateLabel: "Thursday, June 25, 2026",
    kickoffET: "21:00",
    home: "Cape Verde",
    away: "Saudi Arabia",
    city: "Houston",
    citySlug: "houston",
    stadium: "NRG Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 62,
    stage: "Group stage",
    group: "H",
    date: "2026-06-25",
    dateLabel: "Thursday, June 25, 2026",
    kickoffET: "21:00",
    home: "Uruguay",
    away: "Spain",
    city: "Guadalajara",
    citySlug: "guadalajara",
    stadium: "Estadio Akron",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 63,
    stage: "Group stage",
    group: "G",
    date: "2026-06-26",
    dateLabel: "Friday, June 26, 2026",
    kickoffET: "00:00",
    home: "Egypt",
    away: "Iran",
    city: "Seattle",
    citySlug: "seattle",
    stadium: "Lumen Field",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 64,
    stage: "Group stage",
    group: "G",
    date: "2026-06-26",
    dateLabel: "Friday, June 26, 2026",
    kickoffET: "00:00",
    home: "New Zealand",
    away: "Belgium",
    city: "Vancouver",
    citySlug: "vancouver",
    stadium: "BC Place",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 65,
    stage: "Group stage",
    group: "I",
    date: "2026-06-26",
    dateLabel: "Friday, June 26, 2026",
    kickoffET: "16:00",
    home: "Norway",
    away: "France",
    city: "Boston",
    citySlug: "boston",
    stadium: "Gillette Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 66,
    stage: "Group stage",
    group: "I",
    date: "2026-06-26",
    dateLabel: "Friday, June 26, 2026",
    kickoffET: "16:00",
    home: "Senegal",
    away: "Iraq",
    city: "Toronto",
    citySlug: "toronto",
    stadium: "BMO Field",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 67,
    stage: "Group stage",
    group: "K",
    date: "2026-06-26",
    dateLabel: "Friday, June 26, 2026",
    kickoffET: "20:30",
    home: "Colombia",
    away: "Portugal",
    city: "Miami",
    citySlug: "miami",
    stadium: "Hard Rock Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 68,
    stage: "Group stage",
    group: "K",
    date: "2026-06-26",
    dateLabel: "Friday, June 26, 2026",
    kickoffET: "20:30",
    home: "DR Congo",
    away: "Uzbekistan",
    city: "Atlanta",
    citySlug: "atlanta",
    stadium: "Mercedes-Benz Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 69,
    stage: "Group stage",
    group: "J",
    date: "2026-06-26",
    dateLabel: "Friday, June 26, 2026",
    kickoffET: "23:00",
    home: "Algeria",
    away: "Austria",
    city: "Kansas City",
    citySlug: "kansas-city",
    stadium: "GEHA Field at Arrowhead Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 70,
    stage: "Group stage",
    group: "J",
    date: "2026-06-26",
    dateLabel: "Friday, June 26, 2026",
    kickoffET: "23:00",
    home: "Jordan",
    away: "Argentina",
    city: "Dallas",
    citySlug: "dallas",
    stadium: "AT&T Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 71,
    stage: "Group stage",
    group: "L",
    date: "2026-06-27",
    dateLabel: "Saturday, June 27, 2026",
    kickoffET: "18:00",
    home: "Panama",
    away: "England",
    city: "New York New Jersey",
    citySlug: "new-york",
    stadium: "MetLife Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 72,
    stage: "Group stage",
    group: "L",
    date: "2026-06-27",
    dateLabel: "Saturday, June 27, 2026",
    kickoffET: "18:00",
    home: "Croatia",
    away: "Ghana",
    city: "Philadelphia",
    citySlug: "philadelphia",
    stadium: "Lincoln Financial Field",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 73,
    stage: "Round of 32",
    group: "",
    date: "2026-06-28",
    dateLabel: "Sunday, June 28, 2026",
    kickoffET: "15:00",
    home: "2A",
    away: "2B",
    city: "Los Angeles",
    citySlug: "los-angeles",
    stadium: "SoFi Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 74,
    stage: "Round of 32",
    group: "",
    date: "2026-06-29",
    dateLabel: "Monday, June 29, 2026",
    kickoffET: "13:00",
    home: "1C",
    away: "2F",
    city: "Houston",
    citySlug: "houston",
    stadium: "NRG Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 75,
    stage: "Round of 32",
    group: "",
    date: "2026-06-29",
    dateLabel: "Monday, June 29, 2026",
    kickoffET: "16:30",
    home: "1E",
    away: "3ACDF",
    city: "Boston",
    citySlug: "boston",
    stadium: "Gillette Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 76,
    stage: "Round of 32",
    group: "",
    date: "2026-06-29",
    dateLabel: "Monday, June 29, 2026",
    kickoffET: "20:00",
    home: "1F",
    away: "2C",
    city: "Monterrey",
    citySlug: "monterrey",
    stadium: "Estadio BBVA",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 77,
    stage: "Round of 32",
    group: "",
    date: "2026-06-29",
    dateLabel: "Monday, June 29, 2026",
    kickoffET: "21:00",
    home: "1A",
    away: "3CEFHI",
    city: "Mexico City",
    citySlug: "mexico-city",
    stadium: "Estadio Banorte",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 78,
    stage: "Round of 32",
    group: "",
    date: "2026-06-30",
    dateLabel: "Tuesday, June 30, 2026",
    kickoffET: "13:00",
    home: "2E",
    away: "2I",
    city: "Dallas",
    citySlug: "dallas",
    stadium: "AT&T Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 79,
    stage: "Round of 32",
    group: "",
    date: "2026-06-30",
    dateLabel: "Tuesday, June 30, 2026",
    kickoffET: "17:00",
    home: "1I",
    away: "3CDFGH",
    city: "New York New Jersey",
    citySlug: "new-york",
    stadium: "MetLife Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 80,
    stage: "Round of 32",
    group: "",
    date: "2026-06-30",
    dateLabel: "Tuesday, June 30, 2026",
    kickoffET: "20:00",
    home: "1D",
    away: "3BEFIJ",
    city: "San Francisco Bay Area",
    citySlug: "san-francisco",
    stadium: "Levi's Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 81,
    stage: "Round of 32",
    group: "",
    date: "2026-07-01",
    dateLabel: "Wednesday, July 1, 2026",
    kickoffET: "12:00",
    home: "1L",
    away: "3EHIJK",
    city: "Atlanta",
    citySlug: "atlanta",
    stadium: "Mercedes-Benz Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 82,
    stage: "Round of 32",
    group: "",
    date: "2026-07-01",
    dateLabel: "Wednesday, July 1, 2026",
    kickoffET: "16:00",
    home: "1G",
    away: "3AEHIJ",
    city: "Seattle",
    citySlug: "seattle",
    stadium: "Lumen Field",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 83,
    stage: "Round of 32",
    group: "",
    date: "2026-07-02",
    dateLabel: "Thursday, July 2, 2026",
    kickoffET: "15:00",
    home: "1H",
    away: "2J",
    city: "Los Angeles",
    citySlug: "los-angeles",
    stadium: "SoFi Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 84,
    stage: "Round of 32",
    group: "",
    date: "2026-07-02",
    dateLabel: "Thursday, July 2, 2026",
    kickoffET: "19:00",
    home: "2K",
    away: "2L",
    city: "Toronto",
    citySlug: "toronto",
    stadium: "BMO Field",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 85,
    stage: "Round of 32",
    group: "",
    date: "2026-07-02",
    dateLabel: "Thursday, July 2, 2026",
    kickoffET: "23:00",
    home: "1B",
    away: "3EFGIJ",
    city: "Vancouver",
    citySlug: "vancouver",
    stadium: "BC Place",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 86,
    stage: "Round of 32",
    group: "",
    date: "2026-07-03",
    dateLabel: "Friday, July 3, 2026",
    kickoffET: "14:00",
    home: "2D",
    away: "2G",
    city: "Dallas",
    citySlug: "dallas",
    stadium: "AT&T Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 87,
    stage: "Round of 32",
    group: "",
    date: "2026-07-03",
    dateLabel: "Friday, July 3, 2026",
    kickoffET: "18:00",
    home: "1J",
    away: "2H",
    city: "Miami",
    citySlug: "miami",
    stadium: "Hard Rock Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 88,
    stage: "Round of 32",
    group: "",
    date: "2026-07-03",
    dateLabel: "Friday, July 3, 2026",
    kickoffET: "21:30",
    home: "1K",
    away: "3DEIJL",
    city: "Kansas City",
    citySlug: "kansas-city",
    stadium: "GEHA Field at Arrowhead Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 89,
    stage: "Round of 16",
    group: "",
    date: "2026-07-04",
    dateLabel: "Saturday, July 4, 2026",
    kickoffET: "15:00",
    home: "W73",
    away: "W76",
    city: "Houston",
    citySlug: "houston",
    stadium: "NRG Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 90,
    stage: "Round of 16",
    group: "",
    date: "2026-07-04",
    dateLabel: "Saturday, July 4, 2026",
    kickoffET: "19:00",
    home: "W74",
    away: "W78",
    city: "Los Angeles",
    citySlug: "los-angeles",
    stadium: "SoFi Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 91,
    stage: "Round of 16",
    group: "",
    date: "2026-07-04",
    dateLabel: "Saturday, July 4, 2026",
    kickoffET: "21:00",
    home: "W75",
    away: "W77",
    city: "New York New Jersey",
    citySlug: "new-york",
    stadium: "MetLife Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 92,
    stage: "Round of 16",
    group: "",
    date: "2026-07-05",
    dateLabel: "Sunday, July 5, 2026",
    kickoffET: "18:00",
    home: "W79",
    away: "W81",
    city: "Philadelphia",
    citySlug: "philadelphia",
    stadium: "Lincoln Financial Field",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 93,
    stage: "Round of 16",
    group: "",
    date: "2026-07-05",
    dateLabel: "Sunday, July 5, 2026",
    kickoffET: "21:00",
    home: "W80",
    away: "W82",
    city: "Seattle",
    citySlug: "seattle",
    stadium: "Lumen Field",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 94,
    stage: "Round of 16",
    group: "",
    date: "2026-07-06",
    dateLabel: "Monday, July 6, 2026",
    kickoffET: "17:00",
    home: "W83",
    away: "W84",
    city: "Dallas",
    citySlug: "dallas",
    stadium: "AT&T Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 95,
    stage: "Round of 16",
    group: "",
    date: "2026-07-06",
    dateLabel: "Monday, July 6, 2026",
    kickoffET: "21:00",
    home: "W85",
    away: "W88",
    city: "Atlanta",
    citySlug: "atlanta",
    stadium: "Mercedes-Benz Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 96,
    stage: "Round of 16",
    group: "",
    date: "2026-07-07",
    dateLabel: "Tuesday, July 7, 2026",
    kickoffET: "21:00",
    home: "W86",
    away: "W87",
    city: "Boston",
    citySlug: "boston",
    stadium: "Gillette Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 97,
    stage: "Quarter-finals",
    group: "",
    date: "2026-07-09",
    dateLabel: "Thursday, July 9, 2026",
    kickoffET: "18:00",
    home: "W89",
    away: "W90",
    city: "Boston",
    citySlug: "boston",
    stadium: "Gillette Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 98,
    stage: "Quarter-finals",
    group: "",
    date: "2026-07-10",
    dateLabel: "Friday, July 10, 2026",
    kickoffET: "19:00",
    home: "W91",
    away: "W92",
    city: "Los Angeles",
    citySlug: "los-angeles",
    stadium: "SoFi Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 99,
    stage: "Quarter-finals",
    group: "",
    date: "2026-07-11",
    dateLabel: "Saturday, July 11, 2026",
    kickoffET: "16:00",
    home: "W93",
    away: "W94",
    city: "Miami",
    citySlug: "miami",
    stadium: "Hard Rock Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 100,
    stage: "Quarter-finals",
    group: "",
    date: "2026-07-11",
    dateLabel: "Saturday, July 11, 2026",
    kickoffET: "21:00",
    home: "W95",
    away: "W96",
    city: "Kansas City",
    citySlug: "kansas-city",
    stadium: "GEHA Field at Arrowhead Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 101,
    stage: "Semi-finals",
    group: "",
    date: "2026-07-14",
    dateLabel: "Tuesday, July 14, 2026",
    kickoffET: "20:00",
    home: "W97",
    away: "W98",
    city: "Dallas",
    citySlug: "dallas",
    stadium: "AT&T Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 102,
    stage: "Semi-finals",
    group: "",
    date: "2026-07-15",
    dateLabel: "Wednesday, July 15, 2026",
    kickoffET: "20:00",
    home: "W99",
    away: "W100",
    city: "Atlanta",
    citySlug: "atlanta",
    stadium: "Mercedes-Benz Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 103,
    stage: "Bronze final",
    group: "",
    date: "2026-07-18",
    dateLabel: "Saturday, July 18, 2026",
    kickoffET: "16:00",
    home: "L101",
    away: "L102",
    city: "Miami",
    citySlug: "miami",
    stadium: "Hard Rock Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  },
  {
    matchNumber: 104,
    stage: "Final",
    group: "",
    date: "2026-07-19",
    dateLabel: "Sunday, July 19, 2026",
    kickoffET: "16:00",
    home: "W101",
    away: "W102",
    city: "New York New Jersey",
    citySlug: "new-york",
    stadium: "MetLife Stadium",
    sourceStatus: "mapped-from-schedule-html-cross-checked-by-match-order"
  }
];
